# -*- coding: utf-8 -*-
"""tratamento_dados_logistica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127yH_VnAF2j0VrIspMBjHnB5quGGDymC

#criar um fluxo de analise de dados logisticos

-
"""

import pandas as pd

# Carregar CSV
df = pd.read_csv("base_logistica.csv", sep=";")

# Ver primeiras linhas
print(df.head())

# Info da base
print(df.info())

# Converter colunas de datas
df["Data_Pedido"] = pd.to_datetime(df["Data_Pedido"])
df["Data_Envio"] = pd.to_datetime(df["Data_Envio"])
df["Data_Entrega"] = pd.to_datetime(df["Data_Entrega"], errors="coerce")  # permite valores nulos

# Criar colunas úteis
df["Lead_Time"] = (df["Data_Entrega"] - df["Data_Envio"]).dt.days
df["Tempo_Total"] = (df["Data_Entrega"] - df["Data_Pedido"]).dt.days

# Tratar valores nulos (entregas em trânsito)
df["Lead_Time"] = df["Lead_Time"].fillna(-1)   # -1 significa não entregue ainda

# Padronizar nomes de cidades
df["Cidade_Destino"] = df["Cidade_Destino"].str.title().str.strip()

df.to_csv("base_logistica_tratada.csv", index=False, sep=";")

df.to_excel("base_logistica_tratada.xlsx", index=False)